---
- name: Include variables
  include_vars:
    file: ../../vars.yml
    
- name: Download Logstash Deb Package
  get_url:
    url: "{{ logstash_url }}{{logstash_version }}.deb"
    dest: "{{ download }}"
  when: ansible_facts['distribution']=="Ubuntu"

- name: Download Logstash Yum Package
  get_url:
    url: "{{ logstash_url }}{{logstash_version }}.rpm"
    dest: "{{ download }}"
  when: ansible_facts['distribution']=="CentOS"
    
- name: Install Logstash Deb Package
  become: yes
  apt:
    deb: "{{ download }}/{{logstash_version }}.deb"
  when: ansible_facts['distribution']=="Ubuntu"

- name: Install Logstash Yum Package
  become: yes
  yum:
    name: "{{ download }}/{{logstash_version }}.rpm"
    state: present
  when: ansible_facts['distribution']=="CentOS"

- name: Create Logstash Pipeline File
  become: yes
  file:
      path: /etc/logstash/conf.d/main.conf
      state: touch

- name: Add Logstash Pipeline Configuration
  become: yes
  blockinfile:
      path: /etc/logstash/conf.d/main.conf
      marker: ""
      block: |
        input {
          beats {
            port => 5044
          }
        }
        output {
          elasticsearch { hosts => ["192.168.28.71:9200"]
          }
        }

- name: Start Logstash Service
  become: yes
  service:
    name: logstash
    state: started
