---
- name: Include variables
  include_vars:
    file: ../../vars.yml

- name: Download Elastic Deb Package
  get_url:
    url: "{{ elastic_url }}{{ elastic_version }}-amd64.deb"
    dest: "{{ download }}"
  when: ansible_facts['distribution']=="Ubuntu"

- name: Download Elastic Yum Package
  get_url:
    url: "{{ elastic_url }}{{ elastic_version }}-x86_64.rpm"
    dest: "{{ download }}"
  when: ansible_facts['distribution']=="CentOS"

- name: Install Elastic Deb Package
  become: yes
  apt:
    deb: "{{ download }}/{{ elastic_version }}-amd64.deb"
  when: ansible_facts['distribution']=="Ubuntu"

- name: Install Elastic Yum Package
  become: yes
  yum:
    name: "{{ download }}/{{ elastic_version }}-x86_64.rpm"
    state: present
  when: ansible_facts['distribution']=="CentOS"
  
